# SPDX-License-Identifier: GPL-2.0
# Makefile for AMLogic meson video decoder driver

meson-vdec-objs += vdec.o vdec_1.o vdec_hevc.o esparser.o canvas.o codec_helpers.o codec_mpeg12.o codec_h264.o codec_hevc.o vdec_platform.o codec_mpeg4.o codec_mjpeg.o

obj-$(CONFIG_VIDEO_AML_MESON_VDEC) += meson-vdec.o

